## host to bind, can also be passed via CLI args
host = "0.0.0.0"

## port to bind, can also be passed via CLI args
port = 8888

## whether to allow anyone to register an account
open_registration = true

## URI for postgres (using development creds here)
db_uri="postgres://atuin:<pass>@db/atuin"
