#! /bin/sh

# Applications to start on session start
# Intended to be called from bspwmrc or similar wm startup script
#
# desktop cursor theme
xsetroot -cursor_name left_ptr

# mouse wheel
xinput --set-prop "Logitech USB Receiver" "libinput Natural Scrolling Enabled" 1

# keyboard key repeat rate
xset r rate 200 25

# hotkey daemon
sxhkd &

# hotkey daemon
xfce4-power-manager &

# screenshot manager
# spectacle -s &
flameshot &

# layouts and polybar
$HOME/.screenlayout/default.sh
$HOME/.config/polybar/launch.sh &

# input method
fcitx5 &

# window compositor
picom --config "$HOME/.config/picom/picom.conf" &

# notification daemon
dunst &

# clipboard manager
copyq &

# wallpaper manager
nitrogen --restore &
# $HOME/.local/bin/feh-blur &
# feh --bg-fill ~/Pictures/background.jpg &

# extras
# lxpolkit &

