#!/bin/bash

sudo mount -t cifs -o credentials=$HOME/.qnap_credentials,uid=$USER,gid=$USER,iocharset=utf8, //10.178.0.81/Tank $HOME/Tank
sudo mount -t cifs -o credentials=$HOME/.qnap_credentials,uid=$USER,gid=$USER,iocharset=utf8, //10.178.0.81/Media $HOME/Media
