#!/bin/bash

# kill pipewire process
killall -9 pipewire

# reload polybar
sleep 5 && $HOME/.config/polybar/launch.sh

# mouse wheel
xinput --set-prop "Logitech USB Receiver" "libinput Natural Scrolling Enabled" 1

# keyboard key repeat rate
xset r rate 200 25
