#!/bin/bash

# send notification
notify-send 'System' 'reload configs and sound'

# mouse wheel
xinput --set-prop "Logitech USB Receiver" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "Logitech USB Receiver" "libinput Natural Scrolling Enabled Default" 1

# keyboard key repeat rate
xset r rate 200 25

# restart pipewire
# systemctl restart --user pipewire.service

# reload polybar
# sleep 5 && $HOME/.config/polybar/launch.sh
