#!/bin/bash

sleep_icon="/usr/share/icons/Papirus-Dark/48x48/status/state_shutoff.svg"

notify-send -i $sleep_icon 'Swayidle' '\nSleep in 5s';

swayidle -w \
  timeout 5 'hyprctl dispatch dpms off' \
  resume 'hyprctl dispatch dpms on && pkill swayidle' \
  after-resume 'waybar' \
  before-sleep 'pkill waybar' &
