#!/bin/bash

# pkill swayidle

# swayidle -w timeout 1 'swaylock -f -c 000000' \
#   timeout 5 'systemctl suspend' \
#   after-resume 'hyprctl dispatch dpms on' \
#   before-sleep 'swaylock && hyprctl dispatch dpms off' &
