#!/bin/bash

chosen=$(printf "  Restart\n󰈀  Up\n󰈀  Down" | rofi -dmenu -i -theme-str '@import "tailscalemenu.rasi"')

case "$chosen" in
	"  Restart") sudo systemctl restart tailscaled;;
	"󰈀  Up") notify-send 'Tailscale' 'link up.' && sudo tailscale up --accept-routes=true --accept-dns=false;;
	"󰈀  Down") notify-send 'Tailscale' 'link down.' && sudo tailscale down;;
	*) exit 1 ;;
esac
